using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AutoConstructor.Generator;

[Generator]
public class AutoConstructorGenerator : ISourceGenerator
{
    public const string MistmatchTypesDiagnosticId = "ACONS06";

    private static readonly DiagnosticDescriptor Rule = new(
        MistmatchTypesDiagnosticId,
        "Couldn't generate constructor",
        "One or more parameter have mismatching types",
        "Usage",
        DiagnosticSeverity.Error,
        true,
        null,
        $"https://github.com/k94ll13nn3/AutoConstructor#{MistmatchTypesDiagnosticId}",
        WellKnownDiagnosticTags.Build);

    public void Initialize(GeneratorInitializationContext context)
    {
        // Register the attribute source
        context.RegisterForPostInitialization((i) =>
        {
            i.AddSource(Source.AttributeFullName, SourceText.From(Source.AttributeText, Encoding.UTF8));
            i.AddSource(Source.IgnoreAttributeFullName, SourceText.From(Source.IgnoreAttributeText, Encoding.UTF8));
            i.AddSource(Source.InjectAttributeFullName, SourceText.From(Source.InjectAttributeText, Encoding.UTF8));
        });

        // Register a syntax receiver that will be created for each generation pass.
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not SyntaxReceiver receiver)
        {
            return;
        }

        foreach (ClassDeclarationSyntax candidateClass in receiver.CandidateClasses)
        {
            if (context.CancellationToken.IsCancellationRequested)
            {
                break;
            }

            INamedTypeSymbol? symbol = context
                .Compilation
                .GetSemanticModel(candidateClass.SyntaxTree)
                .GetDeclaredSymbol(candidateClass);
            if (symbol is not null)
            {
                string filename = $"{symbol.Name}.g.cs";
                if (!symbol.ContainingNamespace.IsGlobalNamespace)
                {
                    filename = $"{symbol.ContainingNamespace.ToDisplayString()}.{filename}";
                }

                bool emitNullChecks = true;
                if (context.AnalyzerConfigOptions.GlobalOptions.TryGetValue("build_property.AutoConstructor_DisableNullChecking", out string? disableNullCheckingSwitch))
                {
                    emitNullChecks = !disableNullCheckingSwitch.Equals("true", StringComparison.OrdinalIgnoreCase);
                }

                var fields = symbol.GetMembers().OfType<IFieldSymbol>()
                    .Where(x => x.CanBeReferencedByName
                        && !x.IsStatic
                        && x.IsReadOnly
                        && !x.IsInitialized()
                        && !x.HasAttribute(Source.IgnoreAttributeFullName, context.Compilation))
                    .Select(x => GetFieldInfo(x, context.Compilation, emitNullChecks))
                    .ToList();

                if (fields.Count == 0)
                {
                    // No need to report diagnostic, taken care by the analyers.
                    continue;
                }

                if (fields.GroupBy(x => x.ParameterName).Any(g =>
                    g.Where(c => c.Type is not null).Select(c => c.Type).Distinct().Count() > 1
                    || (g.All(c => c.Type is null) && g.Select(c => c.FallbackType).Distinct().Count() > 1)
                    ))
                {
                    context.ReportDiagnostic(Diagnostic.Create(Rule, candidateClass.GetLocation()));
                    continue;
                }

                context.AddSource(filename, SourceText.From(GenerateAutoConstructor(symbol, fields), Encoding.UTF8));
            }
        }
    }

    private static string GenerateAutoConstructor(INamedTypeSymbol symbol, IEnumerable<FieldInfo> fields)
    {
        var constructorParameters = fields
            .GroupBy(x => x.ParameterName)
            .Select(x => x.Any(c => c.Type is not null) ? x.First(c => c.Type is not null) : x.First())
            .ToList();

        var source = new StringBuilder("// <auto-generated />");
        string tabulation = "    ";
        if (fields.Any(f => f.Nullable))
        {
            source.Append(@"
#nullable enable");
        }

        if (symbol.ContainingNamespace.IsGlobalNamespace)
        {
            tabulation = string.Empty;
        }
        else
        {
            source.Append($@"
namespace {symbol.ContainingNamespace.ToDisplayString()}
{{");
        }

        source.Append($@"
{tabulation}partial class {symbol.Name}
{tabulation}{{
{tabulation}    public {symbol.Name}({string.Join(", ", constructorParameters.Select(it => $"{it.Type ?? it.FallbackType} {it.ParameterName}"))})
{tabulation}    {{");

        foreach (FieldInfo field in fields)
        {
            source.Append($@"
{tabulation}        this.{field.FieldName} = {field.Initializer};");
        }
        source.Append($@"
{tabulation}    }}
{tabulation}}}
");
        if (!symbol.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append(@"}
");
        }

        return source.ToString();
    }

    private static FieldInfo GetFieldInfo(IFieldSymbol fieldSymbol, Compilation compilation, bool emitNullChecks)
    {
        ITypeSymbol type = fieldSymbol.Type;
        string? typeDisplay = type.ToDisplayString();
        string parameterName = fieldSymbol.Name.TrimStart('_');
        string initializer = parameterName;

        AttributeData? attributeData = fieldSymbol.GetAttribute(Source.InjectAttributeFullName, compilation);
        if (attributeData is not null)
        {
            ImmutableArray<IParameterSymbol> parameters = attributeData.AttributeConstructor?.Parameters ?? ImmutableArray.Create<IParameterSymbol>();
            if (GetParameterValue("parameterName", parameters, attributeData.ConstructorArguments) is string { Length: > 0 } parameterNameValue)
            {
                parameterName = parameterNameValue;
                initializer = parameterNameValue;
            }

            if (GetParameterValue("initializer", parameters, attributeData.ConstructorArguments) is string { Length: > 0 } initializerValue)
            {
                initializer = initializerValue;
            }

            string? injectedTypeValue = GetParameterValue("injectedType", parameters, attributeData.ConstructorArguments);
            typeDisplay = string.IsNullOrWhiteSpace(injectedTypeValue) ? null : injectedTypeValue;
        }

        if (type.NullableAnnotation != NullableAnnotation.NotAnnotated && emitNullChecks)
        {
            initializer = $"{initializer} ?? throw new System.ArgumentNullException(nameof({parameterName}))";
        }

        return new(
            typeDisplay,
            parameterName,
            fieldSymbol.Name,
            initializer,
            type.ToDisplayString(),
            type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated);
    }

    private static string? GetParameterValue(string parameterName, ImmutableArray<IParameterSymbol> parameters, ImmutableArray<TypedConstant> arguments)
    {
        return parameters.ToList().FindIndex(c => c.Name == parameterName) is int index and not -1
            ? (arguments[index].Value?.ToString())
            : null;
    }
}
